// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EcommerceApp.Models;

public partial class Product
{
    public string ProductId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime ModifedOn { get; set; }
}